### ISSUE TITLE
И снова за работу

### ISSUE THREAD

**Issue by Shemplo** [Shemplo/KSE-and-Digial-Methods#16]
Я знаю, что вы не скучали без этого, но надо хотя бы начать не в последний день 😅

**Comment by AhriWindway** [comment]
Хотелось бы. Будет круто, если где-то тут будет лежать задание.

**Comment by Shemplo** [comment]
> ### Что вообще делаем 
> Моделирование роста монокристаллического твердого раствора *Algan*'а методом хлоридной эпитаксии

### Задание 1

Найти межфазные потоки *Al*-содержащих компонент на поверхности твёрдого алюминия и скорость испарения источника алюминия в зависимости от температуры. 
* Чтобы это сделать, надо решить систему уравнений при различных значениях температуры. 
* Построить диаграммы Аррениуса (графики в системе координат **ln (...)** и **-1/T**)
* Показать, что преобладающим *Al*-содержащим компонентом, выходящим из источника, является трихлорид алюминия *AlCl3*

### Задание 2

Найти межфазные потоки *Ga*-содержащих компонент на поверхности жидкого галлия и скорость испарения источника алюминия в зависимости от температуры. 
* Чтобы это сделать, надо решить систему уравнений при различных значениях температуры. 
* Построить диаграммы Аррениуса (графики в системе координат **ln (...)** и **-1/T**)
* Показать, что преобладающим *Ga*-содержащим компонентом, выходящим из источника, является монохлорид галлия *GaCl*

Там есть ещё одно задание, но нам пока и этого хватит. Вообще в документе с курсовиком 9 страниц описания чего надо делать, поэтому просто берите его с почты и читайте. Тут слишком подробно это не опишешь, чисто спланировать действия. Для чего я предлагаю разделиться на 2 группы:
* **1 группа** (2 человека): каждый берёт на себя 1 из описанных выше заданий
* **2 группа** (2 человека): вместе делают 3 задание, которое, якобы, самое тяжёлое (но это не точно)

Предлагаемое разбиение (@AhriWindway & @MrFiskerton ) ↔ (@Shemplo & @egormkn )

**Comment by Shemplo** [comment]
Вообще, я думаю, что выкладывать сюда файл с сами заданием - не самая лучшая идея. Всё же это интеллектуальная собственность, а репозиторий открытый.

Что касается ЯП для решения задач, то я думаю, что на усмотрение группы, потому что задания в целом, вроде, независимы и не требуют общего интерфейса или что-то в этом роде. Но если это понадобится, то я топлю за **Java**

**Comment by Shemplo** [comment]
Ну так что, на праздниках делаем курсовой проект?

**Comment by Shemplo** [comment]
Вроде, [тут](http://dssp.petrsu.ru/p/tutorial/meth_calc/files/11.shtml) более-менее нормально описано, как решать НСУ

Думаю, что я сегодня-завтра начну и буду писать на **Java**, так что если есть возражения, то самое время это обсудить сейчас 😛

**Comment by Shemplo** [comment]
За оформление README.md в папке *KSE Course work* можно получить "вкусный" приз от @Shemplo.
Надо просто сделать так, чтобы было красиво и понятно 😉

**Comment by Shemplo** [comment]
Иии, сладкий приз уходит @AhriWindway 🎉
